import streamlit as st
import pandas as pd
import plotly.express as px
import os

st.set_page_config(page_title="PredictiChain 2026", layout="wide")
st.title("🛡️ PredictiChain: Strategic Control Tower")

# --- URGENT PATH FIX ---
# This finds the 'PredictiChain' root folder automatically
current_dir = os.path.dirname(os.path.abspath(__file__)) 
project_root = os.path.dirname(os.path.dirname(current_dir)) 

# Use 'Data' with a capital 'D' to match your folder structure
data_path = os.path.join(project_root, 'Backend', 'Data', 'processed', 'final_analytics.csv')

if not os.path.exists(data_path):
    st.error(f"🚨 Backend data not found at: {data_path}")
    st.info("Step 1: Run 'python Backend/src/engine.py' first.")
else:
    df = pd.read_csv(data_path)
    st.success("✅ PredictiChain Engine: Analytics Loaded")

    # KPI HEADER
    c1, c2, c3, c4 = st.columns(4)
    # Using the columns generated by your engine.py
    c1.metric("Revenue @ Risk", f"${df['Revenue_at_Risk'].sum():,.0f}", delta="Action Needed", delta_color="inverse")
    c2.metric("Inventory Carrying Cost", f"${df['Carrying_Cost'].sum():,.0f}")
    c3.metric("Avg Safety Stock", f"{df['Safety_Stock_MT'].mean():.1f} MT")
    c4.metric("Risk Frequency", f"{(df['Disruption_Occurred'].mean()*100):.1f}%")

    # ROOT CAUSE ANALYSIS
    st.markdown("### 🔍 Risk Root Cause Analysis")
    fig = px.scatter(df, x="Vulnerability_Score", y="Safety_Stock_MT", 
                     color="Weather_Condition", size="Weight_MT",
                     hover_data=['Origin_Port', 'Destination_Port'],
                     title="Vulnerability vs. Required Buffer Stock")
    st.plotly_chart(fig, use_container_width=True)

    # ACTIONABLE RECOMMENDATIONS
    st.markdown("### 🛠️ Executive Action Plan")
    high_risk = df[df['Revenue_at_Risk'] > 15000].sort_values('Revenue_at_Risk', ascending=False)
    
    for _, row in high_risk.head(3).iterrows():
        st.warning(f"**Alert**: Shipment {row['Shipment_ID']} on {row['Transport_Mode']} is vulnerable. "
                   f"Impact: **${row['Revenue_at_Risk']:,}**. Recommended Action: Increase safety stock to **{row['Safety_Stock_MT']} MT**.")

    # DEMAND FORECAST
    st.markdown("### 📈 Demand Trend (Forecast)")
    # Ensure date is sorted for the line chart
    df['Date'] = pd.to_datetime(df['Date'])
    forecast_fig = px.line(df.sort_values('Date'), x='Date', y='Predicted_Daily_Demand', title="Predicted Demand Volume")
    st.plotly_chart(forecast_fig, use_container_width=True)